#!/bin/sh
# Utility functions for theming statusbar scripts.

display() {
    if [ -n "$2" ]; then
        color="$2"
    else
        case "$(basename "$0")" in
            spade-bar-batt) color="#65A399" ;;
            spade-bar-date) color="#EA9847" ;;
	    spade-bar-ram)  color="#8AC6F2" ;;
            *) color="#FFFFFF" ;;
        esac
    fi

    echo "^c$color^$1"
}
