#!/bin/sh
# Utility functions for theming statusbar scripts.

display() {
    if [ -n "$2" ]; then
        color="$2"
    else
        case "$(basename "$0")" in
            spade-bar-batt) color="#65A399" ;;
            spade-bar-date) color="#EA9847" ;;
            *) color="#FFFFFF" ;;
        esac
    fi

    case "$STATUSBAR" in
        "dwmblocks")
            echo "^c$color^$1"
            ;;
        *)
            echo "$1"
            ;;
    esac
}
